[package]
name = "sumch"
version = "0.1.1"
authors = ["Li Linfang <nonellf@gmail.com>"]
edition = "2018"

[dependencies]
regex = "1"

[dev-dependencies]
criterion = "0.2"

[[bench]]
name = "my_benchmark"
harness = false
